"""
VLA Provider — KIST DRL G1 Workstation [TASK-40]
================================================

Vendor-agnostic Vision-Language-Action provider. Default backend: NVIDIA
GR00T N1.7 (3B) whole-body model served by KIST's Model Server. ``backend``
is selectable via ``VLAConfig`` so other VLA models can slot in without
consumer changes.

Per CONV-005 (KIST 2026-05-22), VLA is **whole-body** — locomotion and
manipulation are both generated by this model. Per CONV-006, the model
emits action chunks at ~15 Hz (16-step chunks) and the chunks are
unpacked into 100 Hz step-level JointCmd messages here on the PC; NX
sees only step-level commands, not chunks.

Per CONV-007, the GearSonic balance-correction stage lives inside this
provider (post-VLA) until its deployment device is decided (PC GPU /
separate Jetson / NX onboard). The external interface (joint cmd out)
stays the same regardless.

drawio C4 Container:
    Name        : VLA Provider
    Technology  : GR00T N1.7 (3B) client + GearSonic balance correction
    Description : sub-task prompt + obs → balance-corrected JointCmd stream.

---

## Data flow

    TaskSrvProvider                                   (PC)
        ↓ sub-task prompt (Korean / English)
    Move Connector                                    (PC)
        ↓ infer(prompt, obs)
    VLA Provider                                      (this class)
        │ (1) GR00T N1.7 client  → 16-step chunk @ ~15 Hz
        │ (2) GearSonic stage    → balance-corrected joint targets
        │ (3) chunk unpacker     → step-level JointCmd @ 100 Hz
        ↓ publish_joint_cmd(joint_cmd_step)           ← UnitreeG1 Provider hook
    UnitreeG1 Provider                                (PC, TASK-41)
        ↓ /bridge/cmd/arm  (upper body, rt/arm_sdk, weight respected)
        ↓ /bridge/cmd/low  (lower body, rt/lowcmd,  weight ignored)
    NX safety_monitor → motor_controller              (Onboard)

JointCmd carries ``chunk_id`` + ``step_index`` so the NX
``motor_controller`` ring-buffer can detect chunk boundaries for the
optional crossfade fallback (default OFF — canonical crossfade lives
here on the PC).

---

## ICD references

| Direction | Topic / call                                | Note                          |
|-----------|---------------------------------------------|-------------------------------|
| inbound   | infer(prompt, image, joint_state, imu)      | ← Move Connector              |
| inbound   | UnitreeG1 Provider.camera / joint / imu     | RGB + 29-DoF + base/ankle L/R |
| outbound  | KIST Model Server (gRPC / HTTP)             | chunk emission ~15 Hz         |
| outbound  | publish_joint_cmd (via UnitreeG1)           | step replay @ 100 Hz          |

Out-of-scope (deprecated 2026-05-24):
    - VLA Sync Signal to VLM Provider — VLM deferred (REQ-36 [DEPRECATED]).
      Provider does NOT need to publish a sync line.

---

Vendor reference (friend's original scaffold):
    src/providers/example/vla_groot_provider.py  ← GR00T-specific class
    This vendor-agnostic file (``vla_provider.py``) is the active replacement.

---

TODO(REQ-39) [TASK-40]: backend abstraction — ``VLABackend`` interface, GR00T
                        N1.7 default impl. Keep class name vendor-agnostic.
TODO(REQ-39) [TASK-40]: connect to KIST Model Server (gRPC or HTTP — KIST
                        owns the server, we own the client). Skeleton test
                        with dummy chunk while server is in development.
TODO(REQ-31) [TASK-40]: obs assembly — bundle RGB + 29-DoF joint state +
                        IMU (base + ankle L/R) + sub-task prompt.
TODO(REQ-31) [TASK-40]: chunk decode — unpack 16-step action chunk into
                        step-level joint targets with (chunk_id, step_index)
                        metadata.
TODO(REQ-43) [TASK-40]: GearSonic stage — post-VLA balance correction.
                        Spec deferred (KIST 단장님 학생들 담당 — see
                        CONV-007). For now, identity passthrough with a
                        clearly-marked seam where the model will hook in.
TODO(REQ-43) [TASK-40]: GearSonic placement — keep external joint-cmd
                        interface stable so the model can move to a
                        separate device later (PC GPU / Jetson / NX) without
                        breaking Move Connector or UnitreeG1 Provider.
TODO(REQ-31) [TASK-40]: 100 Hz step replay loop — pop chunk steps into the
                        publish path at the configured rate; new chunk
                        arriving mid-replay supersedes pending steps.
TODO(REQ-31) [TASK-40]: PC-side crossfade between consecutive chunks
                        (canonical per CONV-006); NX queue_aggregate is the
                        optional fallback (default OFF).
TODO(REQ-39) [TASK-40]: safety clip — reject out-of-envelope joint targets
                        before they leave this provider.
TODO(REQ-39) [TASK-40]: unit/integration tests under tests/providers/.
"""

import logging
from dataclasses import dataclass
from enum import Enum
from typing import Any, Optional

from .singleton import singleton


class VLABackend(str, Enum):
    """Vision-Language-Action backend selector."""

    GROOT_N17 = "groot_n17"
    # OPENVLA   = "openvla"     # OpenVLA (future)
    # PI0       = "pi0"          # π0 (future)


@dataclass
class VLAConfig:
    """VLA Provider runtime configuration."""

    backend: VLABackend = VLABackend.GROOT_N17
    # Connection to KIST Model Server (KIST owns server, we own client).
    model_server_url: str = "http://localhost:8000"
    model_server_protocol: str = "http"      # "http" | "grpc"
    request_timeout_s: float = 1.0
    # Inference + replay rates (CONV-006).
    action_horizon: int = 16                 # steps per chunk
    chunk_emit_rate_hz: float = 15.0         # GR00T property, fixed-ish
    step_replay_rate_hz: float = 100.0       # NX motor loop rate
    # GearSonic balance-correction stage (CONV-007 — spec deferred).
    gearsonic_enabled: bool = True           # identity passthrough until wired
    gearsonic_device: str = "cuda:0"         # "cuda:0" | "cuda:1" | "cpu"
    # Safety envelope (rejected before leaving the provider).
    joint_delta_clip_rad: float = 0.25
    # Auth / device for the local client side.
    api_key_env: str = "KIST_VLA_API_KEY"


@singleton
class VLAProvider:
    """
    Vendor-agnostic Vision-Language-Action provider.

    Default backend: KIST GR00T N1.7 Model Server (REQ-39). Consumes
    sub-task prompts from the Move Connector, bundles observation
    (camera + 29-DoF joint state + IMU base/ankle L/R) from the UnitreeG1
    Provider, requests a 16-step action chunk from the model server,
    passes the chunk through the GearSonic balance-correction stage
    (CONV-007), then unpacks the chunk into step-level JointCmd messages
    at 100 Hz for the UnitreeG1 Provider publish path.
    """

    def __init__(self, config: Optional[VLAConfig] = None):
        """
        Parameters
        ----------
        config : VLAConfig, optional
            Runtime configuration. Defaults to GR00T N1.7, 15 Hz chunks,
            100 Hz step replay, GearSonic enabled.
        """
        self._config = config or VLAConfig()
        self._running = False
        # Bound late in start() so the UnitreeG1 Provider singleton is up.
        self._unitree_g1 = None
        self._current_chunk_id = 0
        logging.info(
            "VLAProvider: skeleton initialized (backend=%s, server=%s, "
            "chunk_hz=%.1f, replay_hz=%.1f, gearsonic=%s)",
            self._config.backend.value,
            self._config.model_server_url,
            self._config.chunk_emit_rate_hz,
            self._config.step_replay_rate_hz,
            self._config.gearsonic_enabled,
        )

    # ------------------------------------------------------------------
    # Lifecycle
    # ------------------------------------------------------------------
    def start(self) -> None:
        """Connect to the KIST Model Server and bind to UnitreeG1 Provider."""
        # TODO(REQ-39) [TASK-40]: resolve UnitreeG1 Provider singleton
        # TODO(REQ-39) [TASK-40]: open gRPC/HTTP client to model server
        # TODO(REQ-43) [TASK-40]: load GearSonic model (if local) or open
        #                         RPC to the remote device (if separate)
        # TODO(REQ-31) [TASK-40]: spawn step-replay worker thread @ 100 Hz
        raise NotImplementedError("VLAProvider.start: TBD [TASK-40]")

    def stop(self) -> None:
        """Cancel in-flight inference, drain replay queue, close clients."""
        # TODO(REQ-39) [TASK-40]: cancel request, join worker, close client
        raise NotImplementedError("VLAProvider.stop: TBD [TASK-40]")

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------
    async def infer(self, sub_task_prompt: str) -> int:
        """
        Request one VLA chunk for ``sub_task_prompt`` and enqueue its
        steps for the 100 Hz replay loop.

        Observation (camera + joint state + IMU) is read live from the
        UnitreeG1 Provider — callers do NOT pass it in. This keeps the
        Move Connector API minimal (prompt-only).

        Parameters
        ----------
        sub_task_prompt : str
            Natural-language sub-task from the Move Connector
            (TaskSrvProvider scenario step).

        Returns
        -------
        int
            ``chunk_id`` assigned to the resulting 16-step chunk. The
            ``step_index`` runs 0..15 inside the chunk. Step-level
            JointCmd messages will carry ``(chunk_id, step_index)``.
        """
        # TODO(REQ-31) [TASK-40]: snapshot obs from UnitreeG1 Provider
        # TODO(REQ-39) [TASK-40]: send (prompt, obs) to KIST Model Server
        # TODO(REQ-43) [TASK-40]: pipe chunk through GearSonic stage
        # TODO(REQ-39) [TASK-40]: safety clip (joint_delta_clip_rad)
        # TODO(REQ-31) [TASK-40]: enqueue 16 steps with new chunk_id; the
        #                         replay loop will publish them at 100 Hz
        raise NotImplementedError("VLAProvider.infer: TBD [TASK-40]")

    def cancel_chunk(self) -> None:
        """Drop the currently replaying chunk (called on E-STOP / new prompt)."""
        # TODO(REQ-31) [TASK-40]: flush replay queue, hold joint state
        raise NotImplementedError("VLAProvider.cancel_chunk: TBD [TASK-40]")

    # ------------------------------------------------------------------
    # Internals — GearSonic seam (CONV-007)
    # ------------------------------------------------------------------
    def _gearsonic_correct(self, chunk: Any) -> Any:
        """
        Post-VLA balance correction (GearSonic stage).

        Spec deferred — see CONV-007 + REQ-43 (KIST 단장님 학생들 담당).
        For now this is the seam where the model hooks in; default
        behaviour is identity passthrough so the rest of the pipeline
        can be built and tested.
        """
        # TODO(REQ-43) [TASK-40]: when spec lands, run model here:
        #     corrected = self._gearsonic(chunk, imu_base, imu_ankle_l, imu_ankle_r)
        # TODO(REQ-43) [TASK-40]: if placement moves off-PC (Jetson / NX),
        #                         keep this method's signature; only the
        #                         transport changes (local call → RPC).
        return chunk  # identity passthrough placeholder

    # ------------------------------------------------------------------
    # Internals — chunk → step unpack (CONV-006)
    # ------------------------------------------------------------------
    def _enqueue_chunk_steps(self, chunk: Any, chunk_id: int) -> None:
        """
        Unpack a 16-step chunk into the 100 Hz replay queue.

        Each enqueued step carries ``(chunk_id, step_index)`` so the NX
        ``motor_controller`` ring-buffer can detect chunk boundaries for
        the optional crossfade fallback (default OFF per CONV-006).
        """
        # TODO(REQ-31) [TASK-40]: drain pending queue, push 16 fresh steps
        # TODO(REQ-31) [TASK-40]: PC-side crossfade between chunk_id N and
        #                         N+1 (canonical per CONV-006)
        raise NotImplementedError("VLAProvider._enqueue_chunk_steps: TBD [TASK-40]")
